spring.application.name=nonstopplatformapi
spring.datasource.url=jdbc:mysql://localhost:3306/non_stop
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true